
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-project-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-project-6
  template:
    metadata:
      labels:
        app: mlops-project-6
    spec:
      containers:
      - name: mlops-project-6
        image: us-central1-docker.pkg.dev/serious-cat-455501-d2/mlops-project-6/mlops-project-6:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-project-6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
