version: 2.1

executors:
  docker-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Autheticate with google cloud
          command:  | 
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > serious-cat-455501-d2-b450dcd81756.json
              gcloud auth activate-service-account  --key-file=serious-cat-455501-d2-b450dcd81756.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker
      - run:
          name: Build and Push image
          command: |
              docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-project-6/mlops-project-6:latest .
              docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-project-6/mlops-project-6:latest         

  deploy_to_gke:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Autheticate with google cloud
          command:  | 
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > serious-cat-455501-d2-b450dcd81756.json
              gcloud auth activate-service-account  --key-file=serious-cat-455501-d2-b450dcd81756.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker
      - run:
          name: Configure GKE
          command: |
             gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      
      - run:
          name: Deploy to GKE
          command: |
              kubectl apply -f kubernetes-deployment.yaml


workflows:
  version: 2
  deployment_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image
     


